package ma.fstm.ilisi2.projects.biblio.model.bo;
// Generated 26 févr. 2023 19:21:54 by Hibernate Tools 4.3.1



/**
 * Livre generated by hbm2java
 */
public class Livre  implements java.io.Serializable {


     private String isbn;
     private String titre;

    public Livre() {
    }

	
    public Livre(String isbn) {
        this.isbn = isbn;
    }
    public Livre(String isbn, String titre) {
       this.isbn = isbn;
       this.titre = titre;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }




}


